#!/usr/bin/env python3
"""Generate a static Tauri updater manifest."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True, help="Release version, for example 0.4.2")
    parser.add_argument(
        "--platform",
        required=True,
        action="append",
        help="Tauri platform key, for example linux-x86_64, darwin-aarch64 or windows-x86_64",
    )
    parser.add_argument(
        "--url",
        required=True,
        action="append",
        help="HTTPS URL of the updater bundle",
    )
    parser.add_argument(
        "--signature-file",
        required=True,
        action="append",
        type=Path,
        help="Path to the .sig file generated by the Tauri build",
    )
    parser.add_argument("--notes", default="", help="Release notes included in latest.json")
    parser.add_argument(
        "--output",
        default=Path("latest.json"),
        type=Path,
        help="Manifest output path",
    )
    return parser.parse_args()


def build_manifest(
    *,
    version: str,
    notes: str,
    platforms: list[str],
    urls: list[str],
    signature_files: list[Path],
) -> dict:
    if not (len(platforms) == len(urls) == len(signature_files)):
        raise ValueError(
            "--platform, --url and --signature-file must be provided the same number of times"
        )

    platform_entries = {}
    for platform, url, signature_file in zip(platforms, urls, signature_files):
        if platform in platform_entries:
            raise ValueError(f"Duplicate updater platform: {platform}")
        signature = signature_file.read_text(encoding="utf-8").strip()
        platform_entries[platform] = {
            "signature": signature,
            "url": url,
        }

    return {
        "version": version,
        "notes": notes,
        "pub_date": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "platforms": platform_entries,
    }


def main() -> int:
    args = parse_args()
    try:
        manifest = build_manifest(
            version=args.version,
            notes=args.notes,
            platforms=args.platform,
            urls=args.url,
            signature_files=args.signature_file,
        )
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote Tauri updater manifest: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
