#!/usr/bin/env python3
"""Generate a static Tauri updater manifest."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True, help="Release version, for example 0.4.2")
    parser.add_argument(
        "--platform",
        required=True,
        help="Tauri platform key, for example linux-x86_64, darwin-aarch64 or windows-x86_64",
    )
    parser.add_argument("--url", required=True, help="HTTPS URL of the updater bundle")
    parser.add_argument(
        "--signature-file",
        required=True,
        type=Path,
        help="Path to the .sig file generated by the Tauri build",
    )
    parser.add_argument("--notes", default="", help="Release notes included in latest.json")
    parser.add_argument(
        "--output",
        default=Path("latest.json"),
        type=Path,
        help="Manifest output path",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    signature = args.signature_file.read_text(encoding="utf-8").strip()
    manifest = {
        "version": args.version,
        "notes": args.notes,
        "pub_date": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "platforms": {
            args.platform: {
                "signature": signature,
                "url": args.url,
            }
        },
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote Tauri updater manifest: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
